### ISSUE TITLE
Molecule-Test Failed

### ISSUE THREAD

**Issue by alevieux** [labordep/molecule#1]
3 tests not work:

- MolMySocketTest 
Missing class:  MolMySocketComponentImpl, MolMyClientComponentImpl

- MolMyTableTest 
Missing class: MolMyTableComponentImpl, MolMyUserComponentImpl

- MolMyWarningSystemTest 
Missing class: MolMyWarnerComponentImpl, MolMyListenerComponentImpl

**Comment by labordep** [comment]
Thanks alevieux, we are producing a newer version with the correction.
